#!/bin/bash

source "$HOME/.config/.colors"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins/plugins_cute"


SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
FONT_FACE="AurulentSansM Nerd Font"
##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top \
height=33 \
color=$TRS_PINK_MIDLE \
topmost=off \
shadow=5 \
blur_radius=0.9\
shadow.color=$PINK_DARK\
shadow.angle=90\
shadow.distance=2\

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="3270 Nerd Font"
  icon.font.size=16
  label.font="AurulentSansM Nerd Font"
  label.font.size=14
  icon.color=$BLACK
  label.color=$BLACK
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.corner_radius=5 
  background.color=$BLUE_LIGHT
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
CUSTOM_ICONS=("󰨡 " "" "" "󱥁" "" "󰍺" "7" "8" "9" "10")
CUSTOM_LABELS=("Start" "インターネット" "Code" "チャット" "Other" "2 モニター" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${CUSTOM_ICONS[i]}"
	icon.color=$PINK_DARK
    icon.padding_left=7
    icon.padding_right=3
    background.height=25
	background.drawing=on
	label.drawing=on
#	label="${CUSTOM_LABELS[i]}"
	label.font.size=11
	label.align=center
	background.shadow.drawing=on
	background.shadow.color=$PINK_DARK
	background.shadow.angle=220
	background.shadow.distance=2
    script="$PLUGIN_DIR/custom_selected.sh"
    click_script="yabai -m space --focus $sid"
  )
sketchybar	 --add item clock left \
           	 --set clock update_freq=10 icon=  script="$PLUGIN_DIR/misha_clock.sh"  \
  			 --add space space."$sid" left --set space."$sid" "${space[@]}" 
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set
#source "$PLUGIN_DIR/image.sh" left "zaku.gif"
sketchybar --add item front_app center \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/custom_front_app.sh" \
           --subscribe front_app front_app_switched
#source "$PLUGIN_DIR/image.sh" right "char_2_left.jpg"
##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/misha_volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/misha_battery.sh" \
           --subscribe battery system_woke power_source_change


sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE" \
	icon.font.size=18 \
    label.drawing=off \
	background.color=$BLUE_LIGHT \
	background.shadow.drawing=on \
	background.shadow.color=$PINK_DARK \
	background.shadow.angle=90 \
	background.shadow.distance=2 \
	background.border_color=$PINK_DARK \
	background.border_width=1\
    label.padding_left=3 \
	label.font.size=7 \
	background.height=25 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
